### ISSUE TITLE
Wanted to count detected objects/bounding boxes in object detection app. 

### ISSUE THREAD

**Issue by NafiuNurRashid** [pytorch/android-demo-app#109]
I wanted to count the detected object/ bounding boxes as integer value in this object detection app. how can I do that? 
![screenshot2 jpg](https://user-images.githubusercontent.com/44752690/111318815-98fb8d80-868f-11eb-971a-19976a7d7a84.png)
In this image there are three objects detected so the output value will be 3. I added two textView by 
private TextView textView,textView2; in MainActivity.java and 
textView = findViewById(R.id.textView);
textView2 = findViewById(R.id.textView2);
in onCreate function in MainActivity.java.

Here, textView2 is the output value which will show the total value of the objects that are detected after clicking DETECT button.

@jeffxtang

**Comment by jeffxtang** [comment]
Just use the size of the ArrayList [`results`](https://github.com/pytorch/android-demo-app/blob/master/ObjectDetection/app/src/main/java/org/pytorch/demo/objectdetection/MainActivity.java#L226).
