### ISSUE TITLE
Hardcoded value in the Object Detection App

### ISSUE THREAD

**Issue by masum74** [pytorch/android-demo-app#130]
Hi! Do I need to change the hardcoded value '85' to '11' in the ObjectDetection/.../PrePostProcessor.java file (line 143) for a customized model with 6 classes?

` Result result = new Result(cls, outputs[i*85+4], rect);`

When I kept the value as is, all the detected boundaries are on the top left corner of the screen in Live mode (First image). When I changed it to 11 all the boundaries are on the left side (2nd image). 

Am I having this issue because the model is not well trained? Or is it related to this hardcoded value or something else?

Image1:
![img1](https://user-images.githubusercontent.com/8327297/115304215-adb9be00-a132-11eb-88a0-7f9a0fa6dff4.jpg)

Image2:
![img2](https://user-images.githubusercontent.com/8327297/115304220-b14d4500-a132-11eb-86e6-6ab634caadc8.jpg)

**Comment by jeffxtang** [comment]
Most likely it's because of the hardcoded value - the 85 in `Result result = new Result(cls, outputs[i*85+4], rect);` should be replaced with `mOutputColumn` and the 85 in `private static int mOutputColumn = 85;` should be changed to 11 for your customized model. Please see if this works.

**Comment by masum74** [comment]
Thanks for your response. I resolved the problem. I actually replaced the yolov5s.torchscript.pt file with my version in the MainActivity.java file. However, didn't replace the .pt file in the ObjectActivity.java.

**Comment by xugaoxiang** [comment]
> Thanks for your response. I resolved the problem. I actually replaced the yolov5s.torchscript.pt file with my version in the MainActivity.java file. However, didn't replace the .pt file in the ObjectActivity.java.

You sure?
