### ISSUE TITLE
How to add Model Inference Time to yolov5 demo when using live function? Like the iOS demo?

### ISSUE THREAD

**Issue by zxsitu** [pytorch/android-demo-app#156]
Dear developer, I watched this repository (for Android) yolov5 application test video and I compared another repository (for iOS) yolov5 application test video.
I found that the Android application is missing the provision of " Model Inference Time" for real time detection, could you please add it? If not, could you please tell me how to add it? Thank you.
![yolov5_Android](https://user-images.githubusercontent.com/61718945/122684823-64711200-d23a-11eb-9911-ef87a0682102.png)
![yolov5_ios](https://user-images.githubusercontent.com/61718945/122684824-663ad580-d23a-11eb-9be2-5be9c595c89a.png)

**Comment by ilem777** [comment]
Does anyone know how to add inference time?
