### ISSUE TITLE
android studio error

### ISSUE THREAD

**Issue by mathpopo** [pytorch/android-demo-app#18]
* What went wrong:
A problem occurred configuring root project 'PyTorchDemoApp'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not download guava.jar (com.google.guava:guava:27.0.1-jre)
      > Could not get resource 'https://jcenter.bintray.com/com/google/guava/guava/27.0.1-jre/guava-27.0.1-jre.jar'.
         > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/e1c814fd04492a27c38e0317eabeaa1b3e950ec8010239e400fe90ad6c9107b4?response-content-disposition=attachment%3Bfilename%3D%22guava-27.0.1-jre.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvZTFjODE0ZmQwNDQ5MmEyN2MzOGUwMzE3ZWFiZWFhMWIzZTk1MGVjODAxMDIzOWU0MDBmZTkwYWQ2YzkxMDdiND9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmd1YXZhLTI3LjAuMS1qcmUuamFyJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTcxMDI1NzgzfSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=EHYRkIOE9b6FTEOUxmoECRNEqBb0yEv49UZyjwwQhCM~Qp9Oh4LDSPQpOlt7QqzyzWEtXoAOfCvqMi7ishga9KTSuxVnPTL97x4bcwdCpXaKafO4ItobvV5qTHgq-2OQ9hNa2E-Bwgyild6XYKMLbkGTOS~OGw6-IPB0I-galaLp8PuyucOlqOryk42zkA1B3OjD90vkPmTNX3bcHHn1WTgWtRSjkVKYzJjuHMWS9nH9iRl1mGOMHpJiGkNtclPijzs5fJASbcAFMgVHrePbFPfRkt7PHzeYcjv15XVED861e1S0sZCfylzUuVEhK~Xsmt-gVr~Tfl30Auu-SmvjuA__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
            > Remote host closed connection during handshake
   > Could not download kotlin-reflect.jar (org.jetbrains.kotlin:kotlin-reflect:1.3.41)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.3.41/kotlin-reflect-1.3.41.jar'.
         > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/01d469878c6853a607baaadf869c7474b971abe6dd2cb74f244bea0ffb453c76?response-content-disposition=attachment%3Bfilename%3D%22kotlin-reflect-1.3.41.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvMDFkNDY5ODc4YzY4NTNhNjA3YmFhYWRmODY5Yzc0NzRiOTcxYWJlNmRkMmNiNzRmMjQ0YmVhMGZmYjQ1M2M3Nj9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmtvdGxpbi1yZWZsZWN0LTEuMy40MS5qYXIlMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NzEwMjYwMDV9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=pCzHEnqNcs~JgV~Lvjh7Jeo8x0anu6j~NVTjQMY4pyeucxMztAp0yk49rAAmyB5seSOOlh2zBOvkd0m-Y03zMepQAf6eZuP4puRg7yzdcrYtFHkxCOBpNAKF7zQaBsPV5wRP2rtjU9EgN7BeAQBfVD~OPXurG0MmOMvgBe3Zid0yqWftqsW~QtfyMf~fLhFoka1C6FEI9jkYm5KHZH0thgP~~QroRGXnEk0gztEWwSsgyRiwMo~mQyNlNGeRvAmKY~nbXQUskFbii0lWF9hXbl-HudNe7S7Sxh6~BmFIOX9GkMFYtsIwNbn99nbDblVCz9kUZ2pFaGfuoORvRKhQyQ__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
            > Remote host closed connection during handshake
   > Could not download gson.jar (com.google.code.gson:gson:2.8.5)
      > Could not get resource 'https://jcenter.bintray.com/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar'.
         > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/233a0149fc365c9f6edbd683cfe266b19bdc773be98eabdaf6b3c924b48e7d81?response-content-disposition=attachment%3Bfilename%3D%22gson-2.8.5.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvMjMzYTAxNDlmYzM2NWM5ZjZlZGJkNjgzY2ZlMjY2YjE5YmRjNzczYmU5OGVhYmRhZjZiM2M5MjRiNDhlN2Q4MT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmdzb24tMi44LjUuamFyJTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTcxMDI2MjY0fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=qXpeTJuzG3V-wDnfMv6-eo1tPnyFai1BQvjYlCMAvsNtFwsM-Yzmd-biMwLamXtOmXQIksKEjRj7IG0GJLhgz0HqknxUx7-N~UOckqlfjnc6JR-WdfrdW8jIgQBud-24SVV9a~zlovQV60iAex88zGf~juZmVo1GfTw77~PpeWFfrKBLfr4ZjvWim~qbpLHY1Ta6Dlqel4BK9GDpfFV4sdfQk2qznMFcWTNXkiCSN2N73mdKkw0HlEoTJkKHz6bjuFywDLbu-lKvMjR5g0qKfi5hUmqi30y-MKafZWWAK9-nzc-JSF1IGXPlhhaKg48ja0sAcllwL7kA-zi5FCeG~g__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
            > Remote host closed connection during handshake
   > Could not download kotlin-stdlib.jar (org.jetbrains.kotlin:kotlin-stdlib:1.3.41)
      > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.3.41/kotlin-stdlib-1.3.41.jar'.
         > Could not GET 'https://d29vzk4ow07wi7.cloudfront.net/6ea3d0921b26919b286f05cbdb906266666a36f9a7c096197114f7495708ffbc?response-content-disposition=attachment%3Bfilename%3D%22kotlin-stdlib-1.3.41.jar%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvNmVhM2QwOTIxYjI2OTE5YjI4NmYwNWNiZGI5MDYyNjY2NjZhMzZmOWE3YzA5NjE5NzExNGY3NDk1NzA4ZmZiYz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmtvdGxpbi1zdGRsaWItMS4zLjQxLmphciUyMiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTU3MTAyNjA3OX0sIklwQWRkcmVzcyI6eyJBV1M6U291cmNlSXAiOiIwLjAuMC4wLzAifX19XX0_&Signature=awbpB4ceHoK4aUaLTGO3zo3Oy3Lc3QwMUdnPHLzYeSSFkLPgJJ5Qxx~sqZSTMzuXgul9f0SK-LJxROkTv-GpM~QZsRT-7pFEohVRK~XU2zaageDNj5GcEIP~yL880DbUqGxDn-fHZYb0nkB8noQS9OnwXBchO4fN7Ql~sDc-2QkZ6I0ohkfqmg-PCCZHiPMZPnSdovvL6605y6XosgzMHOjrl~orSx0ggB2~2DFg4Ah9w2HmmB3Nm7GhTpdtP4QEsUtnDjnwCCAfPR3wLQW~sai~--zSwG0UTdwIgE68LuBBz6dpEFw7jywRKJdYQ38rJjj8Xs4grQlOuH68cnE5Yw__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'.
            > Remote host closed connection during handshake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by IvanKobzarev** [comment]
Hello @mathpopo,
Manually links from your log work for me and I can download them: 
'https://jcenter.bintray.com/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar'
'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.3.41/kotlin-stdlib-1.3.41.jar'
etc.

I do not know if it is your case or not, but if you need to setup proxy,
you may specify it in `PyTorchDemoApp/gradle.properties` or globally for your machine in `~/.gradle/gradle.properties`:
```
systemProp.http.proxyHost=host
systemProp.http.proxyPort=8080
systemProp.https.proxyHost=host
systemProp.https.proxyPort=8080
```

As another option:
According to `cls && ./gradlew app:dependencies`
those dependencies are necessary only for `lintClassPath` gradle task.

You can skip lint tasks if you add 
`gradle=build -x lint -x lintVitalRelease` to `PyTorchDemoApp/gradle.properties`

Please message if it is still does not work and which configurations you also tried.
