### ISSUE TITLE
Exported model has 80 classes, even though exporting a 10 classes model

### ISSUE THREAD

**Issue by simbertrand** [pytorch/android-demo-app#187]
Hello there,

Thank you for your work, i've been successfully able to use the application with the default coco128 dataset (the one that has 80 classes). Though, I am interested in making it work with a custom model that I made using yolov5. The model has 10 classes, and the inference through the python project works perfectly. I tried doing the same steps as you did (exporting to .plt), and even though there are no errors, when using it in the app, the predictions are weird.
![image](https://user-images.githubusercontent.com/61748650/135920215-6e02e2cd-d5f6-47ac-8e3f-9c33c4a3cda4.png)
I found while using the debugger that the outputTensor is of the shape [1,25200,85], and looking into the outputs array in the function outputsToNMSPredictions, I could clearly see that there were 80 probabilities for every detected object. (and if I change the value of mOutputColumn back to 85, the application works perfectly, but for the coco128 model...).
![Capture](https://user-images.githubusercontent.com/61748650/135919797-3db8fc38-9349-4fc5-9d35-d7c974360526.JPG)
My guess is that my model is not correctly exported to the .ptl format and somehow it loads a "default" model (coco128) for the export. Though i can see in the debugger that the number of classes is 10 while exporting.
![Capture2](https://user-images.githubusercontent.com/61748650/135922093-4e007453-9d9e-4a94-8be9-1d6a0747b110.JPG)
I am no master of programming and the English language so if there's anything unclear let me know!
And yes, I checked that I exported the right file in Android Studio!

Thank you for your help!

**Comment by goldentimecoolk** [comment]
Hi, I have the same problem. How did you solve it?
