### ISSUE TITLE
Problems of Object Detection，APP crash

### ISSUE THREAD

**Issue by tangning9495** [pytorch/android-demo-app#228]
I run the object detection demo. Package the apk and install apk on device, but  it always crashed where I run it on Android VM or a real phone. Anybody can help me? It's my first time to develop android app.

**Comment by cloveropen** [comment]
maybe the scores length and the label length are not equal

**Comment by tangning9495** [comment]
I try to debug the apk and get the bug info:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{org.pytorch.demo.objectdetection/org.pytorch.demo.objectdetection.MainActivity}: com.facebook.jni.CppException: PytorchStreamReader failed locating file bytecode.pkl: file not found ()`

but I can't find the real problem. You mean that the results is defferent from the length of classes in classes.txt file? I rewrite the new classes file, also use the original yolov5s.pt and original txt file, it always crash when I run the apk.

**Comment by tangning9495** [comment]
> maybe the scores length and the label length are not equal

I try to debug the apk and get the bug info:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{org.pytorch.demo.objectdetection/org.pytorch.demo.objectdetection.MainActivity}: com.facebook.jni.CppException: PytorchStreamReader failed locating file bytecode.pkl: file not found ()`

but I can't find the real problem. You mean that the results is defferent from the length of classes in classes.txt file? I rewrite the new classes file, also use the original yolov5s.pt and original txt file, it always crash when I run the apk.

**Comment by FlamingJay** [comment]
> > maybe the scores length and the label length are not equal
> 
> I try to debug the apk and get the bug info: `java.lang.RuntimeException: Unable to start activity ComponentInfo{org.pytorch.demo.objectdetection/org.pytorch.demo.objectdetection.MainActivity}: com.facebook.jni.CppException: PytorchStreamReader failed locating file bytecode.pkl: file not found ()`
> 
> but I can't find the real problem. You mean that the results is defferent from the length of classes in classes.txt file? I rewrite the new classes file, also use the original yolov5s.pt and original txt file, it always crash when I run the apk.


hey, i met this issue also.  i solved it in following ways:
1. generate yolov5s.torchscript.ptl using the **origion repo**
2. use the cmd: python3 export.py --weights=yolov5s.pt --include=torchscript **--optimize**  or python export.py --weights=yolov5s.pt --include=torchscript --optimize
from the export.py, we can know it uses the 'save' func but not the '_save_for_lite_interpreter' func.
3.use the **correct version of android plugins**: pytorch_android_lite and pytorch_android_torchvision_lite  which corresponding to your pytorch which generates ptl file
3.
