### ISSUE TITLE
Exporting .pt to .ptl

### ISSUE THREAD

**Issue by Akotkar23** [pytorch/android-demo-app#231]
I am trying to export .pt file to .ptl but it is converting as .torchscript 
Also, my custom pytorch model file is of 14.4MB and converted .torchscript file is of 28.7MB
How to fix this issue.

**Comment by YeetMasterYeet** [comment]
hello, i am having the exact same issue, any way to fix it?

**Comment by danurrahmajati** [comment]
i tray to convert it too, the detection is not working, Do you have any solution?

**Comment by karuneshpalekar** [comment]
I am facing the same issue, does anybody know the solution ?

**Comment by karuneshpalekar** [comment]
There is a workaround for the same. We need to clone the other tag instead of the current one to get this working . One need to clone the repo in the following manner : git clone --depth 1 --branch v6.0 https://github.com/ultralytics/yolov5  instead of just cloning the recent tag.
