### ISSUE TITLE
Lite Interpreter version number does not match.

### ISSUE THREAD

**Issue by ahmadbajwa8282** [pytorch/android-demo-app#263]
Caused by: com.facebook.jni.CppException: Lite Interpreter version number does not match. The model version must be between 3 and 7 but the model version is 8 ()
    Exception raised from parseMethods at ../torch/csrc/jit/mobile/import.cpp:317 (most recent call first):
    (no backtrace available)

```
import torch
from torch.utils.mobile_optimizer import optimize_for_mobile

model = torch.hub.load('pytorch/vision:v0.10.0', 'deeplabv3_resnet50', pretrained=True)
model.eval()

scripted_module = torch.jit.script(model)
# Export full jit version model (not compatible mobile interpreter), leave it here for comparison
scripted_module.save("deeplabv3_scripted.pt")
# Export mobile interpreter version model (compatible with mobile interpreter)
optimized_scripted_module = optimize_for_mobile(scripted_module)
optimized_scripted_module._save_for_lite_interpreter("deeplabv3_scripted.ptl")
```

**Comment by ahmadbajwa8282** [comment]
@supremassi  try old version of python and PyTorch

**Comment by HripsimeS** [comment]
@ahmadbajwa8282 Hello. Which version of python and PyTorch versions helped you to fix the issue with  Lite Interpreter version?
Thank you very much in advance!

**Comment by SLchowis** [comment]
@HripsimeS , @ahmadbajwa8282 

Here is what you can refer to [Convert between different model versions.](https://stackoverflow.com/questions/71379743/any-idea-of-to-solve-the-version-problem-of-pytorch-model-on-android-device-the)
