### ISSUE TITLE
Are half precision models supported?

### ISSUE THREAD

**Issue by MengAjin** [pytorch/android-demo-app#30]
Hello, I successfully run models on android following thees demos. When I want to use model.half() and trace tensor in half precision to accelerate the process, tracing models in half precision seems ok. However, I can not find toHalf() in the Tensor java class.

Is the half precision supported now?

**Comment by IvanKobzarev** [comment]
Hello @MengAjin,
Unfortunately at the moment we do not support half precision on java side. We will think about to support it.

For quantized model in demo we still use float32 inputs, but inference is in 8bit.

**Comment by dreiss** [comment]
Java doesn't support half-precision floats, so I think your best option is to have your forward method start by calling input.half(), then you can just pass in single-precision float as input.
