### ISSUE TITLE
NMS in android

### ISSUE THREAD

**Issue by philipshurpik** [pytorch/android-demo-app#32]
Hi!

Have a question - how to implement Non Maximum Suppression in Android application?

As I understand - maybe it's to compile with this C++ code for NMS:
https://github.com/pytorch/vision/blob/master/torchvision/csrc/cpu/nms_cpu.cpp
But in that case I need to add also torch dependencies to compilation somehow...

Maybe there is the better way?
* Some Android Java NMS implementations ? (was unable to find it after one hour of googling) 
* Or maybe somehow to implement it with pytorch and then script it with torch.jit.script ?

Would be grateful for help :)

**Comment by IvanKobzarev** [comment]
Helllo @philipshurpik 
I would recommend to ask your questions on https://discuss.pytorch.org/c/mobile or in https://github.com/pytorch/pytorch/issues as more pytorch people will see it.

**Comment by dreiss** [comment]
I think this is the relevant topic: https://discuss.pytorch.org/t/torchvision-android-torchvision-ops-when-will-they-be-available-on-mobile/61360
