### ISSUE TITLE
Worse performance on mobile when using custom model

### ISSUE THREAD

**Issue by IsaacBerman** [pytorch/android-demo-app#38]
I have a custom model that is a variation on YOLOv3, to test the results, I have asserted that the inputTensor on device is the same as that I am loading on the computer. The output (which has detections and classifications) is giving near identical object and class confidences. However, the locations (x,y,w,h) are slightly off. Is this expected behaviour? Do you know if there is anything in particular I should investigate in my model or the trace of my model?

**Comment by dreiss** [comment]
Did you ever figure out what was causing this?
