### ISSUE TITLE
Does this approach support Java in nvidia-gpu? So GRU or LSTM ?

### ISSUE THREAD

**Issue by whaozl** [pytorch/android-demo-app#44]
above.

**Comment by IvanKobzarev** [comment]
Hello @whaozl ,
At the moment pytorch mobile is CPU only, no GPU support.
But we have plan to support it in future, stay tuned.

**Comment by whaozl** [comment]
Thank you very much to help me. I see. 
I always feel that pytorch should support Java like TensorFlow, and currently it is also possible to support CPU.
