### ISSUE TITLE
Legacy model format is not supported on mobile.

### ISSUE THREAD

**Issue by Rokuki** [pytorch/android-demo-app#53]
Error: 
```
Caused by: com.facebook.jni.CppException: Legacy model format is not supported on mobile. (deserialize at /var/lib/jenkins/workspace/torch/csrc/jit/import.cpp:201)
```

Custom MobileNet v2 model, trained with **PyTorch 1.4.0**  and convert to the `pt` file.

build.gradle
```
    implementation 'org.pytorch:pytorch_android:1.4.0-SNAPSHOT'
    implementation 'org.pytorch:pytorch_android_torchvision:1.4.0-SNAPSHOT'
```

But the strange thing is, the other FaceNet model that I use before, it works on both 1.3.0 and 1.4.0. 

Could someone help me please? thanks :)

**Comment by Rokuki** [comment]
solved it

**Comment by Rokuki** [comment]
```
conda install pytorch torchvision cpuonly -c pytorch-nightly
```

**Comment by Rokuki** [comment]
This is very strange.
When I change the traced/scripted  ouput name to `xxx.pt`, the error happens.
```
Caused by: com.facebook.jni.CppException: Legacy model format is not supported on mobile. (deserialize at /var/lib/jenkins/workspace/torch/csrc/jit/import.cpp:201)

```
But, if I add `model` into the `pt` file as `xxx_model.pt`

It works. lol

**Comment by maZna** [comment]
> This is very strange.
> When I change the traced/scripted ouput name to `xxx.pt`, the error happens.
> 
> ```
> Caused by: com.facebook.jni.CppException: Legacy model format is not supported on mobile. (deserialize at /var/lib/jenkins/workspace/torch/csrc/jit/import.cpp:201)
> ```
> 
> But, if I add `model` into the `pt` file as `xxx_model.pt`
> 
> It works. lol

I did not expect this to work but it did.

I had a trained RNN model in a file named 'best_rnn_model.pt". I changed the name to the format described by @Rokuki to ```xxx_model.pt``` specifically, ```rnn_model.pt``` and the subsequent application worked! Sigh!

**Comment by rebelate** [comment]
> > This is very strange.
> > When I change the traced/scripted ouput name to `xxx.pt`, the error happens.
> > ```
> > Caused by: com.facebook.jni.CppException: Legacy model format is not supported on mobile. (deserialize at /var/lib/jenkins/workspace/torch/csrc/jit/import.cpp:201)
> > ```
> > 
> > 
> > But, if I add `model` into the `pt` file as `xxx_model.pt`
> > It works. lol
> 
> I did not expect this to work but it did.
> 
> I had a trained RNN model in a file named 'best_rnn_model.pt". I changed the name to the format described by @Rokuki to `xxx_model.pt` specifically, `rnn_model.pt` and the subsequent application worked! Sigh!

i spent hours figuring this legacy model format thing, and all i found  "different version, pytorch & pytorch_android..." 
but turned out to be naming format? :)
