### ISSUE TITLE
How can I get more than one input in the forward?(Android studio,Java)

### ISSUE THREAD

**Issue by AME430** [pytorch/android-demo-app#64]
In my own model, I need three input tensors,but now i still can't solve this problem. It seems that Ivalue from only accept one tensor.  So what can I do to send three inputs in my model? 
   code:
    final Tensor outputTensor = module.forward(IValue.from(inputTensor1,inputTensor2)).toTensor();

**Comment by dreiss** [comment]
`Module.forward` accepts a variable number of arguments https://pytorch.org/docs/master/org/pytorch/Module.html#org.pytorch.Module.forward(IValue) , so you should be able to use `module.forward(IValue.from(inputTensor1), IValue.from(inputTensor2))`
