### ISSUE TITLE
Multiple outputs 

### ISSUE THREAD

**Issue by mgarbade** [pytorch/android-demo-app#69]
This line in the example expects a single vector as network output: 

    final float[] scores = outputTensor.getDataAsFloatArray();

Is there a function that accepts multiple outputs from the model?

**Comment by dreiss** [comment]
The model can only return one output, but that output can be a tuple of objects.  In TorchScript, write `return (obj1, obj2)`, and in Java, write `module.forward(...).toTuple();`
